message(STATUS "Project create: Core/Engine")
add_subdirectory("src/core/engine")
message(STATUS "Project create: Core/Editor")
add_subdirectory("src/core/editor")
add_dependencies(Editor Engine)
message(STATUS "Project create: Core/AppCore")
add_subdirectory("src/core/appcore")
add_dependencies(AppCore Editor)
add_dependencies(AppCore Engine)

message(STATUS "Project create: App/Panels/Asset")
add_subdirectory("src/app/panels/asset")
add_dependencies(Creator_Asset Engine)
add_dependencies(Creator_Asset Editor)
add_dependencies(Creator_Asset AppCore)
message(STATUS "Project create: App/Panels/Code_Editor")
add_subdirectory("src/app/panels/code_editor")
add_dependencies(Creator_CodeEditor Engine)
add_dependencies(Creator_CodeEditor Editor)
add_dependencies(Creator_CodeEditor AppCore)
message(STATUS "Project create: App/Panels/Console")
add_subdirectory("src/app/panels/console")
add_dependencies(Creator_Console Engine)
add_dependencies(Creator_Console Editor)
add_dependencies(Creator_Console AppCore)
message(STATUS "Project create: App/Panels/Debug")
add_subdirectory("src/app/panels/debug")
add_dependencies(Creator_Debug Engine)
add_dependencies(Creator_Debug Editor)
add_dependencies(Creator_Debug AppCore)
message(STATUS "Project create: App/Panels/Export")
add_subdirectory("src/app/panels/export")
add_dependencies(Creator_Export Engine)
add_dependencies(Creator_Export Editor)
add_dependencies(Creator_Export AppCore)
message(STATUS "Project create: App/Panels/File_Explorer")
add_subdirectory("src/app/panels/explorer")
add_dependencies(Creator_FileExplorer Engine)
add_dependencies(Creator_FileExplorer Editor)
add_dependencies(Creator_FileExplorer AppCore)
message(STATUS "Project create: App/Panels/FramebufferView")
add_subdirectory("src/app/panels/framebuffer_view")
add_dependencies(Creator_FramebufferView Engine)
add_dependencies(Creator_FramebufferView Editor)
add_dependencies(Creator_FramebufferView AppCore)
message(STATUS "Project create: App/Panels/Helper")
add_subdirectory("src/app/panels/helper")
add_dependencies(Creator_Helper Engine)
add_dependencies(Creator_Helper Editor)
add_dependencies(Creator_Helper AppCore)
message(STATUS "Project create: App/Panels/Hierarchy")
add_subdirectory("src/app/panels/hierarchy")
add_dependencies(Creator_Hierarchy Engine)
add_dependencies(Creator_Hierarchy Editor)
add_dependencies(Creator_Hierarchy AppCore)
message(STATUS "Project create: App/Panels/Node_Editor")
add_subdirectory("src/app/panels/node")
add_dependencies(Creator_Node Engine)
add_dependencies(Creator_Node Editor)
add_dependencies(Creator_Node AppCore)
message(STATUS "Project create: App/Panels/Project_Creation")
add_subdirectory("src/app/panels/project_creation")
add_dependencies(Creator_ProjectCreation Engine)
add_dependencies(Creator_ProjectCreation Editor)
add_dependencies(Creator_ProjectCreation AppCore)
add_dependencies(Creator_ProjectCreation Creator_FileExplorer)
message(STATUS "Project create: App/Panels/Property")
add_subdirectory("src/app/panels/property")
add_dependencies(Creator_Property Engine)
add_dependencies(Creator_Property Editor)
add_dependencies(Creator_Property AppCore)
message(STATUS "Project create: App/Panels/Scene")
add_subdirectory("src/app/panels/scene")
add_dependencies(Creator_Scene Engine)
add_dependencies(Creator_Scene Editor)
add_dependencies(Creator_Scene AppCore)
message(STATUS "Project create: App/Panels/Setting")
add_subdirectory("src/app/panels/setting")
add_dependencies(Creator_Setting Engine)
add_dependencies(Creator_Setting Editor)
add_dependencies(Creator_Setting AppCore)
message(STATUS "Project create: App/Panels/Timeline")
add_subdirectory("src/app/panels/timeline")
add_dependencies(Creator_Timeline Engine)
add_dependencies(Creator_Timeline Editor)
add_dependencies(Creator_Timeline AppCore)

message(STATUS "Project create: App/Creator")
add_subdirectory("src/app/creator")
add_dependencies(Creator Editor)
add_dependencies(Creator Engine)
add_dependencies(Creator AppCore)
add_dependencies(Creator Creator_Asset)
add_dependencies(Creator Creator_CodeEditor)
add_dependencies(Creator Creator_Console)
add_dependencies(Creator Creator_Debug)
add_dependencies(Creator Creator_Export)
add_dependencies(Creator Creator_FileExplorer)
add_dependencies(Creator Creator_FramebufferView)
add_dependencies(Creator Creator_Helper)
add_dependencies(Creator Creator_Hierarchy)
add_dependencies(Creator Creator_Node)
add_dependencies(Creator Creator_ProjectCreation)
add_dependencies(Creator Creator_Property)
add_dependencies(Creator Creator_Scene)
add_dependencies(Creator Creator_Setting)
add_dependencies(Creator Creator_Timeline)
